// System changelogs — add new entries at the TOP of the array
// id must be unique and increasing (used to detect "unread" updates)

export const CHANGELOGS = [
  {
    id: 13,
    version: '1.5.1',
    date: '2026-05-08',
    title: 'Control de caja desde el panel admin',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'El administrador puede abrir y cerrar la caja de cualquier tienda desde la sección Pedidos' },
      { type: 'nuevo',     text: 'Worker Panel: el icono de la caja se actualiza en tiempo real vía socket cuando el admin la abre o cierra' },
      { type: 'mejorado',  text: 'Al abrir la caja como admin se registra como "Administrador" en el turno, sin necesidad de un trabajador activo' },
    ],
  },
  {
    id: 12,
    version: '1.5.0',
    date: '2026-05-08',
    title: 'Plataformas de delivery: Rappi, PedidosYa & Uber Eats',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Integración Rappi — recibe pedidos vía webhook en tiempo real' },
      { type: 'nuevo',     text: 'Integración PedidosYa — webhook con soporte de secciones y modificadores' },
      { type: 'nuevo',     text: 'Integración Uber Eats — webhook con soporte de cart.items y optionGroups' },
      { type: 'nuevo',     text: 'Worker Panel: badge de color por plataforma (🛵 Rappi, 🏍️ PedidosYa, 🟢 Uber Eats)' },
      { type: 'nuevo',     text: 'Pedidos externos muestran nombre y teléfono del cliente' },
      { type: 'nuevo',     text: 'Evita duplicados por ID de pedido externo' },
    ],
  },
  {
    id: 11,
    version: '1.4.2',
    date: '2026-05-08',
    title: 'Encuesta de cliente ideal & mejoras de calificaciones',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Nuevo QR de encuesta con 10 preguntas para encontrar al cliente ideal' },
      { type: 'nuevo',     text: 'Panel admin: pestaña "Cliente Ideal" con gráficos de barras por pregunta' },
      { type: 'nuevo',     text: 'Respuestas individuales con fecha en el panel de calificaciones' },
      { type: 'mejorado',  text: 'Calificaciones ahora tiene pestañas separadas: Calificaciones / Cliente Ideal' },
    ],
  },
  {
    id: 10,
    version: '1.4.1',
    date: '2026-05-07',
    title: 'Notificación de desconexión mejorada',
    badge: 'mejorado',
    changes: [
      { type: 'mejorado',  text: 'El aviso de "servidor en mantenimiento" ya no ocupa pantalla completa' },
      { type: 'mejorado',  text: 'Ahora es una pequeña barra flotante en la parte inferior con animación suave' },
      { type: 'mejorado',  text: 'Desaparece automáticamente al reconectar sin interrumpir el flujo de trabajo' },
    ],
  },
  {
    id: 9,
    version: '1.4.0',
    date: '2026-05-05',
    title: 'Sistema de tareas semanales',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'El admin puede asignar tareas a trabajadores por día de la semana' },
      { type: 'nuevo',     text: 'Ventana de 1 hora para completar cada tarea' },
      { type: 'nuevo',     text: 'Las tareas se reinician automáticamente cada domingo' },
      { type: 'nuevo',     text: 'Worker Panel muestra las tareas del día con cuenta regresiva' },
    ],
  },
  {
    id: 8,
    version: '1.3.3',
    date: '2026-04-28',
    title: 'Mejoras en POS y pagos',
    badge: 'mejorado',
    changes: [
      { type: 'mejorado',  text: 'Soporte para múltiples terminales POS por tienda' },
      { type: 'mejorado',  text: 'Métodos de pago personalizables por tienda' },
      { type: 'reparado',  text: 'Corrección en redondeo de totales con descuento' },
      { type: 'reparado',  text: 'Fix en impresión de tickets cuando el producto fue eliminado' },
    ],
  },
  {
    id: 7,
    version: '1.3.2',
    date: '2026-04-20',
    title: 'Inventario y recetas',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Gestión de materias primas con stock mínimo y costo' },
      { type: 'nuevo',     text: 'Recetas: vincula productos/extras a materias primas' },
      { type: 'mejorado',  text: 'Descuento automático de stock al confirmar pedidos' },
      { type: 'reparado',  text: 'Fix en filtros de inventario por categoría' },
    ],
  },
  {
    id: 6,
    version: '1.3.1',
    date: '2026-04-12',
    title: 'Caja y registro diario',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Apertura y cierre de caja por turno de trabajador' },
      { type: 'nuevo',     text: 'Informe PDF del día al cerrar caja (enviado al dueño)' },
      { type: 'mejorado',  text: 'Worker Panel: botón de exportar PDF con resumen del día' },
    ],
  },
  {
    id: 5,
    version: '1.3.0',
    date: '2026-04-01',
    title: 'Sistema de plugins',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Marketplace de plugins con instalación en un clic' },
      { type: 'nuevo',     text: 'Workshop para crear y publicar plugins propios' },
      { type: 'nuevo',     text: 'Plugins pueden inyectar UI en tienda pública y panel admin' },
      { type: 'nuevo',     text: 'Plugin de Instagram Auto para publicación automática' },
    ],
  },
  {
    id: 4,
    version: '1.2.0',
    date: '2026-03-15',
    title: 'León IA y analítica avanzada',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'León IA: asistente inteligente con análisis de ventas y sugerencias' },
      { type: 'nuevo',     text: 'Dashboard de analítica con gráficos por hora, día y producto' },
      { type: 'nuevo',     text: 'Top productos más vendidos del período' },
      { type: 'mejorado',  text: 'Exportación de reportes en PDF y Excel' },
    ],
  },
  {
    id: 3,
    version: '1.1.1',
    date: '2026-03-01',
    title: 'Mejoras de rendimiento y correcciones',
    badge: 'reparado',
    changes: [
      { type: 'reparado',  text: 'Fix en carga de menú en conexiones lentas' },
      { type: 'reparado',  text: 'Corrección en cálculo de descuentos con cupones' },
      { type: 'mejorado',  text: 'Carga inicial del panel hasta 40% más rápida' },
      { type: 'mejorado',  text: 'Socket reconnection más estable en redes móviles' },
    ],
  },
  {
    id: 2,
    version: '1.1.0',
    date: '2026-02-14',
    title: 'Multitienda y gestión de trabajadores',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Soporte para múltiples tiendas por cuenta' },
      { type: 'nuevo',     text: 'Roles de trabajadores con permisos configurables' },
      { type: 'nuevo',     text: 'Worker Panel con notificaciones en tiempo real' },
      { type: 'nuevo',     text: 'Cupones de descuento por tienda' },
    ],
  },
  {
    id: 1,
    version: '1.0.0',
    date: '2026-01-01',
    title: 'Lanzamiento inicial de SRServi',
    badge: 'nuevo',
    changes: [
      { type: 'nuevo',     text: 'Panel de administración completo' },
      { type: 'nuevo',     text: 'Tienda pública con carrito y pedidos en línea' },
      { type: 'nuevo',     text: 'Sistema de pedidos con estados en tiempo real' },
      { type: 'nuevo',     text: 'Calificaciones QR post-pedido' },
    ],
  },
];
